//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Dao.QyBllApp
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class QyBllAppEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“QyBllAppEntities”部分中的连接字符串初始化新 QyBllAppEntities 对象。
        /// </summary>
        public QyBllAppEntities() : base("name=QyBllAppEntities", "QyBllAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QyBllAppEntities 对象。
        /// </summary>
        public QyBllAppEntities(string connectionString) : base(connectionString, "QyBllAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 QyBllAppEntities 对象。
        /// </summary>
        public QyBllAppEntities(EntityConnection connection) : base(connection, "QyBllAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<bsDeal> bsDeal
        {
            get
            {
                if ((_bsDeal == null))
                {
                    _bsDeal = base.CreateObjectSet<bsDeal>("bsDeal");
                }
                return _bsDeal;
            }
        }
        private ObjectSet<bsDeal> _bsDeal;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<bsDealTotal> bsDealTotal
        {
            get
            {
                if ((_bsDealTotal == null))
                {
                    _bsDealTotal = base.CreateObjectSet<bsDealTotal>("bsDealTotal");
                }
                return _bsDealTotal;
            }
        }
        private ObjectSet<bsDealTotal> _bsDealTotal;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<bsSalary> bsSalary
        {
            get
            {
                if ((_bsSalary == null))
                {
                    _bsSalary = base.CreateObjectSet<bsSalary>("bsSalary");
                }
                return _bsSalary;
            }
        }
        private ObjectSet<bsSalary> _bsSalary;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<bsSaler> bsSaler
        {
            get
            {
                if ((_bsSaler == null))
                {
                    _bsSaler = base.CreateObjectSet<bsSaler>("bsSaler");
                }
                return _bsSaler;
            }
        }
        private ObjectSet<bsSaler> _bsSaler;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Promote> Promote
        {
            get
            {
                if ((_Promote == null))
                {
                    _Promote = base.CreateObjectSet<Promote>("Promote");
                }
                return _Promote;
            }
        }
        private ObjectSet<Promote> _Promote;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 bsDeal EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobsDeal(bsDeal bsDeal)
        {
            base.AddObject("bsDeal", bsDeal);
        }
    
        /// <summary>
        /// 用于向 bsDealTotal EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobsDealTotal(bsDealTotal bsDealTotal)
        {
            base.AddObject("bsDealTotal", bsDealTotal);
        }
    
        /// <summary>
        /// 用于向 bsSalary EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobsSalary(bsSalary bsSalary)
        {
            base.AddObject("bsSalary", bsSalary);
        }
    
        /// <summary>
        /// 用于向 bsSaler EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTobsSaler(bsSaler bsSaler)
        {
            base.AddObject("bsSaler", bsSaler);
        }
    
        /// <summary>
        /// 用于向 Promote EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPromote(Promote promote)
        {
            base.AddObject("Promote", promote);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QyBllAppModel", Name="bsDeal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bsDeal : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 bsDeal 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static bsDeal CreatebsDeal(global::System.Guid id)
        {
            bsDeal bsDeal = new bsDeal();
            bsDeal.Id = id;
            return bsDeal;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DealDt
        {
            get
            {
                return _DealDt;
            }
            set
            {
                OnDealDtChanging(value);
                ReportPropertyChanging("DealDt");
                _DealDt = StructuralObject.SetValidValue(value, "DealDt");
                ReportPropertyChanged("DealDt");
                OnDealDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _DealDt;
        partial void OnDealDtChanging(Nullable<global::System.DateTime> value);
        partial void OnDealDtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BuyerId
        {
            get
            {
                return _BuyerId;
            }
            set
            {
                OnBuyerIdChanging(value);
                ReportPropertyChanging("BuyerId");
                _BuyerId = StructuralObject.SetValidValue(value, "BuyerId");
                ReportPropertyChanged("BuyerId");
                OnBuyerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _BuyerId;
        partial void OnBuyerIdChanging(Nullable<global::System.Guid> value);
        partial void OnBuyerIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Buyer
        {
            get
            {
                return _Buyer;
            }
            set
            {
                OnBuyerChanging(value);
                ReportPropertyChanging("Buyer");
                _Buyer = StructuralObject.SetValidValue(value, true, "Buyer");
                ReportPropertyChanged("Buyer");
                OnBuyerChanged();
            }
        }
        private global::System.String _Buyer;
        partial void OnBuyerChanging(global::System.String value);
        partial void OnBuyerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> SalerId
        {
            get
            {
                return _SalerId;
            }
            set
            {
                OnSalerIdChanging(value);
                ReportPropertyChanging("SalerId");
                _SalerId = StructuralObject.SetValidValue(value, "SalerId");
                ReportPropertyChanged("SalerId");
                OnSalerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _SalerId;
        partial void OnSalerIdChanging(Nullable<global::System.Guid> value);
        partial void OnSalerIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Saler
        {
            get
            {
                return _Saler;
            }
            set
            {
                OnSalerChanging(value);
                ReportPropertyChanging("Saler");
                _Saler = StructuralObject.SetValidValue(value, true, "Saler");
                ReportPropertyChanged("Saler");
                OnSalerChanged();
            }
        }
        private global::System.String _Saler;
        partial void OnSalerChanging(global::System.String value);
        partial void OnSalerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DealCount
        {
            get
            {
                return _DealCount;
            }
            set
            {
                OnDealCountChanging(value);
                ReportPropertyChanging("DealCount");
                _DealCount = StructuralObject.SetValidValue(value, "DealCount");
                ReportPropertyChanged("DealCount");
                OnDealCountChanged();
            }
        }
        private Nullable<global::System.Int32> _DealCount;
        partial void OnDealCountChanging(Nullable<global::System.Int32> value);
        partial void OnDealCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DealUnit
        {
            get
            {
                return _DealUnit;
            }
            set
            {
                OnDealUnitChanging(value);
                ReportPropertyChanging("DealUnit");
                _DealUnit = StructuralObject.SetValidValue(value, true, "DealUnit");
                ReportPropertyChanged("DealUnit");
                OnDealUnitChanged();
            }
        }
        private global::System.String _DealUnit;
        partial void OnDealUnitChanging(global::System.String value);
        partial void OnDealUnitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DealType
        {
            get
            {
                return _DealType;
            }
            set
            {
                OnDealTypeChanging(value);
                ReportPropertyChanging("DealType");
                _DealType = StructuralObject.SetValidValue(value, true, "DealType");
                ReportPropertyChanged("DealType");
                OnDealTypeChanged();
            }
        }
        private global::System.String _DealType;
        partial void OnDealTypeChanging(global::System.String value);
        partial void OnDealTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> disCount
        {
            get
            {
                return _disCount;
            }
            set
            {
                OndisCountChanging(value);
                ReportPropertyChanging("disCount");
                _disCount = StructuralObject.SetValidValue(value, "disCount");
                ReportPropertyChanged("disCount");
                OndisCountChanged();
            }
        }
        private Nullable<global::System.Decimal> _disCount;
        partial void OndisCountChanging(Nullable<global::System.Decimal> value);
        partial void OndisCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Amonut
        {
            get
            {
                return _Amonut;
            }
            set
            {
                OnAmonutChanging(value);
                ReportPropertyChanging("Amonut");
                _Amonut = StructuralObject.SetValidValue(value, "Amonut");
                ReportPropertyChanged("Amonut");
                OnAmonutChanged();
            }
        }
        private Nullable<global::System.Decimal> _Amonut;
        partial void OnAmonutChanging(Nullable<global::System.Decimal> value);
        partial void OnAmonutChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value, "IsCheck");
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Checker
        {
            get
            {
                return _Checker;
            }
            set
            {
                OnCheckerChanging(value);
                ReportPropertyChanging("Checker");
                _Checker = StructuralObject.SetValidValue(value, true, "Checker");
                ReportPropertyChanged("Checker");
                OnCheckerChanged();
            }
        }
        private global::System.String _Checker;
        partial void OnCheckerChanging(global::System.String value);
        partial void OnCheckerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CheckDt
        {
            get
            {
                return _CheckDt;
            }
            set
            {
                OnCheckDtChanging(value);
                ReportPropertyChanging("CheckDt");
                _CheckDt = StructuralObject.SetValidValue(value, "CheckDt");
                ReportPropertyChanged("CheckDt");
                OnCheckDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CheckDt;
        partial void OnCheckDtChanging(Nullable<global::System.DateTime> value);
        partial void OnCheckDtChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QyBllAppModel", Name="bsDealTotal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bsDealTotal : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 bsDealTotal 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="cycle">Cycle 属性的初始值。</param>
        /// <param name="cycleType">CycleType 属性的初始值。</param>
        public static bsDealTotal CreatebsDealTotal(global::System.Guid id, global::System.String cycle, global::System.String cycleType)
        {
            bsDealTotal bsDealTotal = new bsDealTotal();
            bsDealTotal.Id = id;
            bsDealTotal.Cycle = cycle;
            bsDealTotal.CycleType = cycleType;
            return bsDealTotal;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cycle
        {
            get
            {
                return _Cycle;
            }
            set
            {
                OnCycleChanging(value);
                ReportPropertyChanging("Cycle");
                _Cycle = StructuralObject.SetValidValue(value, false, "Cycle");
                ReportPropertyChanged("Cycle");
                OnCycleChanged();
            }
        }
        private global::System.String _Cycle;
        partial void OnCycleChanging(global::System.String value);
        partial void OnCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CycleType
        {
            get
            {
                return _CycleType;
            }
            set
            {
                OnCycleTypeChanging(value);
                ReportPropertyChanging("CycleType");
                _CycleType = StructuralObject.SetValidValue(value, false, "CycleType");
                ReportPropertyChanged("CycleType");
                OnCycleTypeChanged();
            }
        }
        private global::System.String _CycleType;
        partial void OnCycleTypeChanging(global::System.String value);
        partial void OnCycleTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> bsS_Id
        {
            get
            {
                return _bsS_Id;
            }
            set
            {
                OnbsS_IdChanging(value);
                ReportPropertyChanging("bsS_Id");
                _bsS_Id = StructuralObject.SetValidValue(value, "bsS_Id");
                ReportPropertyChanged("bsS_Id");
                OnbsS_IdChanged();
            }
        }
        private Nullable<global::System.Guid> _bsS_Id;
        partial void OnbsS_IdChanging(Nullable<global::System.Guid> value);
        partial void OnbsS_IdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bsS_Name
        {
            get
            {
                return _bsS_Name;
            }
            set
            {
                OnbsS_NameChanging(value);
                ReportPropertyChanging("bsS_Name");
                _bsS_Name = StructuralObject.SetValidValue(value, true, "bsS_Name");
                ReportPropertyChanged("bsS_Name");
                OnbsS_NameChanged();
            }
        }
        private global::System.String _bsS_Name;
        partial void OnbsS_NameChanging(global::System.String value);
        partial void OnbsS_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bsS_ContactTel
        {
            get
            {
                return _bsS_ContactTel;
            }
            set
            {
                OnbsS_ContactTelChanging(value);
                ReportPropertyChanging("bsS_ContactTel");
                _bsS_ContactTel = StructuralObject.SetValidValue(value, true, "bsS_ContactTel");
                ReportPropertyChanged("bsS_ContactTel");
                OnbsS_ContactTelChanged();
            }
        }
        private global::System.String _bsS_ContactTel;
        partial void OnbsS_ContactTelChanging(global::System.String value);
        partial void OnbsS_ContactTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DealCount
        {
            get
            {
                return _DealCount;
            }
            set
            {
                OnDealCountChanging(value);
                ReportPropertyChanging("DealCount");
                _DealCount = StructuralObject.SetValidValue(value, "DealCount");
                ReportPropertyChanged("DealCount");
                OnDealCountChanged();
            }
        }
        private Nullable<global::System.Int32> _DealCount;
        partial void OnDealCountChanging(Nullable<global::System.Int32> value);
        partial void OnDealCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DealUnit
        {
            get
            {
                return _DealUnit;
            }
            set
            {
                OnDealUnitChanging(value);
                ReportPropertyChanging("DealUnit");
                _DealUnit = StructuralObject.SetValidValue(value, true, "DealUnit");
                ReportPropertyChanged("DealUnit");
                OnDealUnitChanged();
            }
        }
        private global::System.String _DealUnit;
        partial void OnDealUnitChanging(global::System.String value);
        partial void OnDealUnitChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QyBllAppModel", Name="bsSalary")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bsSalary : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 bsSalary 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="cycle">Cycle 属性的初始值。</param>
        /// <param name="cycleType">CycleType 属性的初始值。</param>
        /// <param name="bsS_Id">bsS_Id 属性的初始值。</param>
        /// <param name="bsS_Name">bsS_Name 属性的初始值。</param>
        /// <param name="zTJ">ZTJ 属性的初始值。</param>
        /// <param name="eDJ">EDJ 属性的初始值。</param>
        /// <param name="sDJ">SDJ 属性的初始值。</param>
        /// <param name="jHJL">JHJL 属性的初始值。</param>
        /// <param name="nextFWJL">NextFWJL 属性的初始值。</param>
        /// <param name="jHCJ">JHCJ 属性的初始值。</param>
        /// <param name="sCYJJL">SCYJJL 属性的初始值。</param>
        /// <param name="amount">Amount 属性的初始值。</param>
        public static bsSalary CreatebsSalary(global::System.Guid id, global::System.String cycle, global::System.String cycleType, global::System.Guid bsS_Id, global::System.String bsS_Name, global::System.Decimal zTJ, global::System.Decimal eDJ, global::System.Decimal sDJ, global::System.Decimal jHJL, global::System.Decimal nextFWJL, global::System.Decimal jHCJ, global::System.Decimal sCYJJL, global::System.Decimal amount)
        {
            bsSalary bsSalary = new bsSalary();
            bsSalary.Id = id;
            bsSalary.Cycle = cycle;
            bsSalary.CycleType = cycleType;
            bsSalary.bsS_Id = bsS_Id;
            bsSalary.bsS_Name = bsS_Name;
            bsSalary.ZTJ = zTJ;
            bsSalary.EDJ = eDJ;
            bsSalary.SDJ = sDJ;
            bsSalary.JHJL = jHJL;
            bsSalary.NextFWJL = nextFWJL;
            bsSalary.JHCJ = jHCJ;
            bsSalary.SCYJJL = sCYJJL;
            bsSalary.Amount = amount;
            return bsSalary;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cycle
        {
            get
            {
                return _Cycle;
            }
            set
            {
                OnCycleChanging(value);
                ReportPropertyChanging("Cycle");
                _Cycle = StructuralObject.SetValidValue(value, false, "Cycle");
                ReportPropertyChanged("Cycle");
                OnCycleChanged();
            }
        }
        private global::System.String _Cycle;
        partial void OnCycleChanging(global::System.String value);
        partial void OnCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CycleType
        {
            get
            {
                return _CycleType;
            }
            set
            {
                OnCycleTypeChanging(value);
                ReportPropertyChanging("CycleType");
                _CycleType = StructuralObject.SetValidValue(value, false, "CycleType");
                ReportPropertyChanged("CycleType");
                OnCycleTypeChanged();
            }
        }
        private global::System.String _CycleType;
        partial void OnCycleTypeChanging(global::System.String value);
        partial void OnCycleTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid bsS_Id
        {
            get
            {
                return _bsS_Id;
            }
            set
            {
                OnbsS_IdChanging(value);
                ReportPropertyChanging("bsS_Id");
                _bsS_Id = StructuralObject.SetValidValue(value, "bsS_Id");
                ReportPropertyChanged("bsS_Id");
                OnbsS_IdChanged();
            }
        }
        private global::System.Guid _bsS_Id;
        partial void OnbsS_IdChanging(global::System.Guid value);
        partial void OnbsS_IdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bsS_Name
        {
            get
            {
                return _bsS_Name;
            }
            set
            {
                OnbsS_NameChanging(value);
                ReportPropertyChanging("bsS_Name");
                _bsS_Name = StructuralObject.SetValidValue(value, false, "bsS_Name");
                ReportPropertyChanged("bsS_Name");
                OnbsS_NameChanged();
            }
        }
        private global::System.String _bsS_Name;
        partial void OnbsS_NameChanging(global::System.String value);
        partial void OnbsS_NameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ZTJ
        {
            get
            {
                return _ZTJ;
            }
            set
            {
                OnZTJChanging(value);
                ReportPropertyChanging("ZTJ");
                _ZTJ = StructuralObject.SetValidValue(value, "ZTJ");
                ReportPropertyChanged("ZTJ");
                OnZTJChanged();
            }
        }
        private global::System.Decimal _ZTJ;
        partial void OnZTJChanging(global::System.Decimal value);
        partial void OnZTJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EDJ
        {
            get
            {
                return _EDJ;
            }
            set
            {
                OnEDJChanging(value);
                ReportPropertyChanging("EDJ");
                _EDJ = StructuralObject.SetValidValue(value, "EDJ");
                ReportPropertyChanged("EDJ");
                OnEDJChanged();
            }
        }
        private global::System.Decimal _EDJ;
        partial void OnEDJChanging(global::System.Decimal value);
        partial void OnEDJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SDJ
        {
            get
            {
                return _SDJ;
            }
            set
            {
                OnSDJChanging(value);
                ReportPropertyChanging("SDJ");
                _SDJ = StructuralObject.SetValidValue(value, "SDJ");
                ReportPropertyChanged("SDJ");
                OnSDJChanged();
            }
        }
        private global::System.Decimal _SDJ;
        partial void OnSDJChanging(global::System.Decimal value);
        partial void OnSDJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal JHJL
        {
            get
            {
                return _JHJL;
            }
            set
            {
                OnJHJLChanging(value);
                ReportPropertyChanging("JHJL");
                _JHJL = StructuralObject.SetValidValue(value, "JHJL");
                ReportPropertyChanged("JHJL");
                OnJHJLChanged();
            }
        }
        private global::System.Decimal _JHJL;
        partial void OnJHJLChanging(global::System.Decimal value);
        partial void OnJHJLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal NextFWJL
        {
            get
            {
                return _NextFWJL;
            }
            set
            {
                OnNextFWJLChanging(value);
                ReportPropertyChanging("NextFWJL");
                _NextFWJL = StructuralObject.SetValidValue(value, "NextFWJL");
                ReportPropertyChanged("NextFWJL");
                OnNextFWJLChanged();
            }
        }
        private global::System.Decimal _NextFWJL;
        partial void OnNextFWJLChanging(global::System.Decimal value);
        partial void OnNextFWJLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal JHCJ
        {
            get
            {
                return _JHCJ;
            }
            set
            {
                OnJHCJChanging(value);
                ReportPropertyChanging("JHCJ");
                _JHCJ = StructuralObject.SetValidValue(value, "JHCJ");
                ReportPropertyChanged("JHCJ");
                OnJHCJChanged();
            }
        }
        private global::System.Decimal _JHCJ;
        partial void OnJHCJChanging(global::System.Decimal value);
        partial void OnJHCJChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SCYJJL
        {
            get
            {
                return _SCYJJL;
            }
            set
            {
                OnSCYJJLChanging(value);
                ReportPropertyChanging("SCYJJL");
                _SCYJJL = StructuralObject.SetValidValue(value, "SCYJJL");
                ReportPropertyChanged("SCYJJL");
                OnSCYJJLChanged();
            }
        }
        private global::System.Decimal _SCYJJL;
        partial void OnSCYJJLChanging(global::System.Decimal value);
        partial void OnSCYJJLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value, "Amount");
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QyBllAppModel", Name="bsSaler")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bsSaler : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 bsSaler 对象。
        /// </summary>
        /// <param name="bsE_Id">bsE_Id 属性的初始值。</param>
        public static bsSaler CreatebsSaler(global::System.Guid bsE_Id)
        {
            bsSaler bsSaler = new bsSaler();
            bsSaler.bsE_Id = bsE_Id;
            return bsSaler;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid bsE_Id
        {
            get
            {
                return _bsE_Id;
            }
            set
            {
                if (_bsE_Id != value)
                {
                    OnbsE_IdChanging(value);
                    ReportPropertyChanging("bsE_Id");
                    _bsE_Id = StructuralObject.SetValidValue(value, "bsE_Id");
                    ReportPropertyChanged("bsE_Id");
                    OnbsE_IdChanged();
                }
            }
        }
        private global::System.Guid _bsE_Id;
        partial void OnbsE_IdChanging(global::System.Guid value);
        partial void OnbsE_IdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> bsO_Id
        {
            get
            {
                return _bsO_Id;
            }
            set
            {
                OnbsO_IdChanging(value);
                ReportPropertyChanging("bsO_Id");
                _bsO_Id = StructuralObject.SetValidValue(value, "bsO_Id");
                ReportPropertyChanged("bsO_Id");
                OnbsO_IdChanged();
            }
        }
        private Nullable<global::System.Guid> _bsO_Id;
        partial void OnbsO_IdChanging(Nullable<global::System.Guid> value);
        partial void OnbsO_IdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalerCode
        {
            get
            {
                return _SalerCode;
            }
            set
            {
                OnSalerCodeChanging(value);
                ReportPropertyChanging("SalerCode");
                _SalerCode = StructuralObject.SetValidValue(value, true, "SalerCode");
                ReportPropertyChanged("SalerCode");
                OnSalerCodeChanged();
            }
        }
        private global::System.String _SalerCode;
        partial void OnSalerCodeChanging(global::System.String value);
        partial void OnSalerCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sex
        {
            get
            {
                return _Sex;
            }
            set
            {
                OnSexChanging(value);
                ReportPropertyChanging("Sex");
                _Sex = StructuralObject.SetValidValue(value, true, "Sex");
                ReportPropertyChanged("Sex");
                OnSexChanged();
            }
        }
        private global::System.String _Sex;
        partial void OnSexChanging(global::System.String value);
        partial void OnSexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdCode
        {
            get
            {
                return _IdCode;
            }
            set
            {
                OnIdCodeChanging(value);
                ReportPropertyChanging("IdCode");
                _IdCode = StructuralObject.SetValidValue(value, true, "IdCode");
                ReportPropertyChanged("IdCode");
                OnIdCodeChanged();
            }
        }
        private global::System.String _IdCode;
        partial void OnIdCodeChanging(global::System.String value);
        partial void OnIdCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactTel
        {
            get
            {
                return _ContactTel;
            }
            set
            {
                OnContactTelChanging(value);
                ReportPropertyChanging("ContactTel");
                _ContactTel = StructuralObject.SetValidValue(value, true, "ContactTel");
                ReportPropertyChanged("ContactTel");
                OnContactTelChanged();
            }
        }
        private global::System.String _ContactTel;
        partial void OnContactTelChanging(global::System.String value);
        partial void OnContactTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDt
        {
            get
            {
                return _BirthDt;
            }
            set
            {
                OnBirthDtChanging(value);
                ReportPropertyChanging("BirthDt");
                _BirthDt = StructuralObject.SetValidValue(value, "BirthDt");
                ReportPropertyChanged("BirthDt");
                OnBirthDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDt;
        partial void OnBirthDtChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr
        {
            get
            {
                return _Addr;
            }
            set
            {
                OnAddrChanging(value);
                ReportPropertyChanging("Addr");
                _Addr = StructuralObject.SetValidValue(value, true, "Addr");
                ReportPropertyChanged("Addr");
                OnAddrChanged();
            }
        }
        private global::System.String _Addr;
        partial void OnAddrChanging(global::System.String value);
        partial void OnAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EntryDate
        {
            get
            {
                return _EntryDate;
            }
            set
            {
                OnEntryDateChanging(value);
                ReportPropertyChanging("EntryDate");
                _EntryDate = StructuralObject.SetValidValue(value, "EntryDate");
                ReportPropertyChanged("EntryDate");
                OnEntryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EntryDate;
        partial void OnEntryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEntryDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalerStatus
        {
            get
            {
                return _SalerStatus;
            }
            set
            {
                OnSalerStatusChanging(value);
                ReportPropertyChanging("SalerStatus");
                _SalerStatus = StructuralObject.SetValidValue(value, true, "SalerStatus");
                ReportPropertyChanged("SalerStatus");
                OnSalerStatusChanged();
            }
        }
        private global::System.String _SalerStatus;
        partial void OnSalerStatusChanging(global::System.String value);
        partial void OnSalerStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SalerType
        {
            get
            {
                return _SalerType;
            }
            set
            {
                OnSalerTypeChanging(value);
                ReportPropertyChanging("SalerType");
                _SalerType = StructuralObject.SetValidValue(value, true, "SalerType");
                ReportPropertyChanged("SalerType");
                OnSalerTypeChanged();
            }
        }
        private global::System.String _SalerType;
        partial void OnSalerTypeChanging(global::System.String value);
        partial void OnSalerTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Reference
        {
            get
            {
                return _Reference;
            }
            set
            {
                OnReferenceChanging(value);
                ReportPropertyChanging("Reference");
                _Reference = StructuralObject.SetValidValue(value, true, "Reference");
                ReportPropertyChanged("Reference");
                OnReferenceChanged();
            }
        }
        private global::System.String _Reference;
        partial void OnReferenceChanging(global::System.String value);
        partial void OnReferenceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value, "IsCheck");
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Checker
        {
            get
            {
                return _Checker;
            }
            set
            {
                OnCheckerChanging(value);
                ReportPropertyChanging("Checker");
                _Checker = StructuralObject.SetValidValue(value, true, "Checker");
                ReportPropertyChanged("Checker");
                OnCheckerChanged();
            }
        }
        private global::System.String _Checker;
        partial void OnCheckerChanging(global::System.String value);
        partial void OnCheckerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CheckDt
        {
            get
            {
                return _CheckDt;
            }
            set
            {
                OnCheckDtChanging(value);
                ReportPropertyChanging("CheckDt");
                _CheckDt = StructuralObject.SetValidValue(value, "CheckDt");
                ReportPropertyChanged("CheckDt");
                OnCheckDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CheckDt;
        partial void OnCheckDtChanging(Nullable<global::System.DateTime> value);
        partial void OnCheckDtChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QyBllAppModel", Name="Promote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promote : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Promote 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Promote CreatePromote(global::System.Guid id)
        {
            Promote promote = new Promote();
            promote.Id = id;
            return promote;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> bsS_Id
        {
            get
            {
                return _bsS_Id;
            }
            set
            {
                OnbsS_IdChanging(value);
                ReportPropertyChanging("bsS_Id");
                _bsS_Id = StructuralObject.SetValidValue(value, "bsS_Id");
                ReportPropertyChanged("bsS_Id");
                OnbsS_IdChanged();
            }
        }
        private Nullable<global::System.Guid> _bsS_Id;
        partial void OnbsS_IdChanging(Nullable<global::System.Guid> value);
        partial void OnbsS_IdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PreRank
        {
            get
            {
                return _PreRank;
            }
            set
            {
                OnPreRankChanging(value);
                ReportPropertyChanging("PreRank");
                _PreRank = StructuralObject.SetValidValue(value, true, "PreRank");
                ReportPropertyChanged("PreRank");
                OnPreRankChanged();
            }
        }
        private global::System.String _PreRank;
        partial void OnPreRankChanging(global::System.String value);
        partial void OnPreRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CurrRank
        {
            get
            {
                return _CurrRank;
            }
            set
            {
                OnCurrRankChanging(value);
                ReportPropertyChanging("CurrRank");
                _CurrRank = StructuralObject.SetValidValue(value, true, "CurrRank");
                ReportPropertyChanged("CurrRank");
                OnCurrRankChanged();
            }
        }
        private global::System.String _CurrRank;
        partial void OnCurrRankChanging(global::System.String value);
        partial void OnCurrRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PromoteCondition
        {
            get
            {
                return _PromoteCondition;
            }
            set
            {
                OnPromoteConditionChanging(value);
                ReportPropertyChanging("PromoteCondition");
                _PromoteCondition = StructuralObject.SetValidValue(value, true, "PromoteCondition");
                ReportPropertyChanged("PromoteCondition");
                OnPromoteConditionChanged();
            }
        }
        private global::System.String _PromoteCondition;
        partial void OnPromoteConditionChanging(global::System.String value);
        partial void OnPromoteConditionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PromoteDt
        {
            get
            {
                return _PromoteDt;
            }
            set
            {
                OnPromoteDtChanging(value);
                ReportPropertyChanging("PromoteDt");
                _PromoteDt = StructuralObject.SetValidValue(value, "PromoteDt");
                ReportPropertyChanged("PromoteDt");
                OnPromoteDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _PromoteDt;
        partial void OnPromoteDtChanging(Nullable<global::System.DateTime> value);
        partial void OnPromoteDtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsCheck
        {
            get
            {
                return _IsCheck;
            }
            set
            {
                OnIsCheckChanging(value);
                ReportPropertyChanging("IsCheck");
                _IsCheck = StructuralObject.SetValidValue(value, "IsCheck");
                ReportPropertyChanged("IsCheck");
                OnIsCheckChanged();
            }
        }
        private Nullable<global::System.Int32> _IsCheck;
        partial void OnIsCheckChanging(Nullable<global::System.Int32> value);
        partial void OnIsCheckChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Checker
        {
            get
            {
                return _Checker;
            }
            set
            {
                OnCheckerChanging(value);
                ReportPropertyChanging("Checker");
                _Checker = StructuralObject.SetValidValue(value, true, "Checker");
                ReportPropertyChanged("Checker");
                OnCheckerChanged();
            }
        }
        private global::System.String _Checker;
        partial void OnCheckerChanging(global::System.String value);
        partial void OnCheckerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CheckDt
        {
            get
            {
                return _CheckDt;
            }
            set
            {
                OnCheckDtChanging(value);
                ReportPropertyChanging("CheckDt");
                _CheckDt = StructuralObject.SetValidValue(value, "CheckDt");
                ReportPropertyChanged("CheckDt");
                OnCheckDtChanged();
            }
        }
        private Nullable<global::System.DateTime> _CheckDt;
        partial void OnCheckDtChanging(Nullable<global::System.DateTime> value);
        partial void OnCheckDtChanged();

        #endregion

    }

    #endregion

}
